import {env} from "cloudflare:workers";
import {verifyMessage} from "viem";
import {getCookie,readSession} from "@/lib/x-auth";
import {getPolygonConfig} from "@/lib/polygon";
type Runtime={DB?:D1Database;EVIDENCE?:R2Bucket;SESSION_SECRET?:string};
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,"0")).join("");
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value)))}
async function auth(request:Request,body:{wallet?:`0x${string}`;signature?:`0x${string}`}){const runtime=env as unknown as Runtime,profile=await readSession(getCookie(request,"renda_x_session")),config=getPolygonConfig();if(!runtime.DB||!runtime.EVIDENCE||!runtime.SESSION_SECRET||!profile||!config||!body.wallet||!body.signature||body.wallet.toLowerCase()!==config.arbitratorAddress.toLowerCase())return null;return await verifyMessage({address:config.arbitratorAddress,message:`Renda Signal arbitrator access:${profile.id}`,signature:body.signature})?{...runtime,db:runtime.DB,evidence:runtime.EVIDENCE,secret:runtime.SESSION_SECRET}:null}
export async function GET(request:Request){const runtime=env as unknown as Runtime,url=new URL(request.url),signalId=url.searchParams.get("signal")||"",evidenceId=url.searchParams.get("evidence")||"",index=Number(url.searchParams.get("index")),expires=Number(url.searchParams.get("expires")),token=url.searchParams.get("token")||"";if(!runtime.DB||!runtime.EVIDENCE||!runtime.SESSION_SECRET||!signalId||!evidenceId||!Number.isInteger(index)||expires<Date.now()/1000)return Response.json({error:"Attachment link expired."},{status:403});const value=`${signalId}:${evidenceId}:${index}:${expires}`;if(await hmac(runtime.SESSION_SECRET,value)!==token)return Response.json({error:"Invalid attachment link."},{status:403});const row=await runtime.DB.prepare("SELECT object_key FROM evidence WHERE signal_id=? AND id=?").bind(signalId,evidenceId).first<{object_key:string}>(),keys=row?JSON.parse(row.object_key||"[]") as string[]:[],object=keys[index]?await runtime.EVIDENCE.get(keys[index]):null;if(!object)return Response.json({error:"Attachment not found."},{status:404});return new Response(object.body,{headers:{"content-type":object.httpMetadata?.contentType||"application/octet-stream","content-disposition":`inline; filename="${object.customMetadata?.fileName||"attachment"}"`}})}
export async function POST(request:Request){const body=await request.json() as{wallet?:`0x${string}`;signature?:`0x${string}`;action?:"message";signalId?:string;message?:string},ctx=await auth(request,body);if(!ctx)return Response.json({error:"Connect and authorize the configured arbitrator wallet."},{status:403});await ctx.db.prepare("CREATE TABLE IF NOT EXISTS signal_messages (id TEXT PRIMARY KEY, signal_id TEXT NOT NULL, author_role TEXT NOT NULL, message TEXT NOT NULL, created_at INTEGER NOT NULL)").run();if(body.action==="message"){const message=String(body.message||"").trim().slice(0,2000),signal=await ctx.db.prepare("SELECT id FROM signals WHERE id=? AND status='disputed'").bind(body.signalId).first();if(!signal||!message)return Response.json({error:"Add an arbitrator message."},{status:400});await ctx.db.prepare("INSERT INTO signal_messages (id,signal_id,author_role,message,created_at) VALUES (?,?,'arbitrator',?,?)").bind(crypto.randomUUID(),body.signalId,message,Math.floor(Date.now()/1000)).run();return Response.json({status:"sent"})}const rows=await ctx.db.prepare("SELECT * FROM signals WHERE status='disputed' ORDER BY updated_at DESC").all<Record<string,string|number>>(),expires=Math.floor(Date.now()/1000)+1800;const signals=await Promise.all(rows.results.map(async signal=>{const messages=await ctx.db.prepare("SELECT author_role,message,created_at FROM signal_messages WHERE signal_id=? ORDER BY created_at ASC").bind(signal.id).all(),evidenceRows=await ctx.db.prepare("SELECT id,public_url,object_key,created_at FROM evidence WHERE signal_id=? ORDER BY created_at ASC").bind(signal.id).all<Record<string,string|number>>(),evidence=await Promise.all(evidenceRows.results.map(async row=>{let content:{message?:string;kind?:string;authorRole?:string}={};try{content=JSON.parse(String(row.public_url||"{}"))}catch{}let keys:string[]=[];try{keys=JSON.parse(String(row.object_key||"[]"))}catch{}const attachments=await Promise.all(keys.map(async(key,index)=>{const value=`${signal.id}:${row.id}:${index}:${expires}`,token=await hmac(ctx.secret,value);return{name:key.split("/").pop()?.replace(/^(dispute-)?[0-9a-f-]+-/,"")||"Attachment",url:`/api/signals/arbitration?signal=${encodeURIComponent(String(signal.id))}&evidence=${encodeURIComponent(String(row.id))}&index=${index}&expires=${expires}&token=${token}`}}));return{id:String(row.id),message:content.message||"",kind:content.kind||"submission",authorRole:content.authorRole||"employee",createdAt:Number(row.created_at),attachments}}));return{...signal,messages:messages.results,submissions:evidence.filter(x=>x.kind!=="dispute"),disputeEvidence:evidence.filter(x=>x.kind==="dispute")}}));return Response.json({signals})}
