"use client";
import {FormEvent,useState} from "react";
import {init} from "@nimiq/mini-app-sdk";

type Message={author_role:string;message:string;created_at:number};
type Evidence={id:string;message:string;kind:string;authorRole:string;createdAt:number;attachments:Array<{name:string;url:string}>};
type Signal={id:string;title:string;terms:string;sender_handle:string;target_handle:string;employer_wallet:string;employee_wallet:string;amount_atomic:string;attention_atomic:string;status:string;ruling_employer_atomic?:string;ruling_employee_atomic?:string;employer_settlement_hash?:string;employee_settlement_hash?:string;messages:Message[];evidence:Evidence[]};
type SdkError={error:{message:string}};
const isError=(value:unknown):value is SdkError=>Boolean(value&&typeof value==="object"&&"error" in value),nim=(value:string|number|bigint)=>Number(BigInt(value))/100000;

async function authorize(){const provider=await init({timeout:10000}),challengeResponse=await fetch("/api/auth/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"challenge"})}),challenge=await challengeResponse.json() as{challengeId?:string;message?:string;error?:string};if(!challengeResponse.ok||!challenge.challengeId||!challenge.message)throw new Error(challenge.error||"Could not start authorization.");const signed=await provider.sign(challenge.message);if(isError(signed))throw new Error(signed.error.message);const response=await fetch("/api/auth/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"verify",challengeId:challenge.challengeId,publicKey:signed.publicKey,signature:signed.signature})}),result=await response.json();if(!response.ok)throw new Error(result.error||"This is not the Renda escrow account.");return provider}

export default function NimAdmin(){
 const[signals,setSignals]=useState<Signal[]>([]),[ready,setReady]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState(""),[splits,setSplits]=useState<Record<string,{employer:string;employee:string}>>({}),[replies,setReplies]=useState<Record<string,string>>({});
 async function load(){const response=await fetch("/api/signals/nimiq?admin=1"),result=await response.json();if(!response.ok)throw new Error(result.error||"Could not open the NIM administration queue.");const signals=await Promise.all((result.signals as Signal[]).map(async signal=>{if(signal.status!=="disputed")return signal;const evidenceResponse=await fetch(`/api/signals/nimiq/admin-file?list=1&signalId=${encodeURIComponent(signal.id)}`),evidenceResult=await evidenceResponse.json();return{...signal,evidence:evidenceResponse.ok?evidenceResult.evidence:signal.evidence}}));setSignals(signals)}
 async function open(){setNotice("");try{await authorize();await load();setReady(true)}catch(error){setNotice(error instanceof Error?error.message:"Could not authorize NIM administration.")}}
 async function api(id:string,action:string,extra={}){const response=await fetch("/api/signals/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,...extra})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Could not update this managed request.");return result}
 async function settle(signal:Signal,outcome:"pay"|"refund"|"employer"|"employee",value:bigint,recipient:string){setBusy(`${signal.id}:${outcome}`);setNotice("");try{const provider=await authorize(),ruling=signal.status==="ruling_pending",attention=signal.status==="attention_pending",memo=attention?`RENDA-ATTENTION:${signal.id}`:ruling?`RENDA-RULING-${outcome.toUpperCase()}:${signal.id}`:`RENDA-${outcome.toUpperCase()}:${signal.id}`,sent=await provider.sendBasicTransactionWithData({recipient,value:Number(value),data:memo});if(isError(sent))throw new Error(sent.error.message);let failure="The transaction is still confirming.";for(let attempt=0;attempt<8;attempt++){if(attempt)await new Promise(resolve=>setTimeout(resolve,2000));const response=await fetch("/api/signals/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,action:"settle",outcome:attention?"employee":outcome,txHash:sent})}),result=await response.json();if(response.ok){failure="";break}failure=result.error||failure;if(!/confirmed|network/i.test(failure))break}if(failure)throw new Error(`${failure} Transaction: ${sent}`);await load()}catch(error){setNotice(error instanceof Error?error.message:"Could not settle this NIM request.")}finally{setBusy("")}}
 async function rule(signal:Signal){setBusy(signal.id);setNotice("");try{const split=splits[signal.id]||{employer:"",employee:""},employer=Math.round(Number(split.employer)*100000),employee=Math.round(Number(split.employee)*100000);if(!Number.isSafeInteger(employer)||!Number.isSafeInteger(employee))throw new Error("Enter valid NIM amounts.");await api(signal.id,"arbitrate",{employerAtomic:String(employer),employeeAtomic:String(employee)});await load()}catch(error){setNotice(error instanceof Error?error.message:"Could not save this ruling.")}finally{setBusy("")}}
 async function reply(event:FormEvent,signal:Signal){event.preventDefault();setBusy(signal.id);try{await api(signal.id,"admin_message",{message:replies[signal.id]||""});setReplies(value=>({...value,[signal.id]:""}));await load()}catch(error){setNotice(error instanceof Error?error.message:"Could not send this message.")}finally{setBusy("")}}
 return <section className="arbitration-page nim-admin"><header><span className="eyebrow">MANAGED NIM CONSOLE</span><h1>Administer held NIM.</h1><p>Only the verified Renda escrow account can view disputes or approve outgoing transfers.</p>{!ready&&<button className="primary" onClick={open}>Authorize Renda escrow account</button>}</header>{notice&&<p className="inline-notice">{notice}</p>}{ready&&signals.length===0&&<div className="action-panel"><h3>No NIM actions waiting</h3></div>}<div className="nim-queue">{signals.map(signal=>{
  const total=BigInt(signal.amount_atomic),attention=BigInt(signal.attention_atomic),remaining=total-attention;
  if(signal.status==="disputed")return <article key={signal.id} className="dispute-card arbitrator-case"><div className="case-context"><small>NIM DISPUTE · {signal.id.slice(0,8).toUpperCase()}</small><h2>{signal.title}</h2><p>{signal.sender_handle} → {signal.target_handle}</p><strong>{nim(remaining).toFixed(5)} NIM held</strong><section className="case-brief"><b>EMPLOYER REQUEST</b><p>{signal.terms}</p></section><section className="case-submissions"><b>EMPLOYEE SUBMISSIONS</b>{signal.evidence.filter(item=>item.kind!=="dispute").map(item=><article key={item.id}><p>{item.message||"Submission with attachments"}</p>{item.attachments.length>0&&<div className="review-files">{item.attachments.map(file=><a key={file.url} href={file.url} target="_blank" rel="noreferrer">📎 {file.name}</a>)}</div>}<time>{new Date(item.createdAt*1000).toLocaleString()}</time></article>)}</section><section className="arb-chat"><b>DISPUTE CONVERSATION</b>{[...signal.messages.map(message=>({role:message.author_role,message:message.message,time:message.created_at,attachments:[]})),...signal.evidence.filter(item=>item.kind==="dispute").map(item=>({role:item.authorRole,message:item.message,time:item.createdAt,attachments:item.attachments}))].sort((a,b)=>a.time-b.time).map((message,index)=><div key={index} className={message.role}><strong>{message.role}</strong><p>{message.message}</p>{message.attachments.length>0&&<div className="review-files">{message.attachments.map(file=><a key={file.url} href={file.url} target="_blank" rel="noreferrer">📎 {file.name}</a>)}</div>}</div>)}</section><form onSubmit={event=>reply(event,signal)}><textarea value={replies[signal.id]||""} onChange={event=>setReplies(value=>({...value,[signal.id]:event.target.value}))} placeholder="Reply as NIM administrator…" required/><button className="secondary">Send reply</button></form></div><div className="ruling-panel"><h3>Final ruling</h3><p>The amounts must total {nim(remaining).toFixed(5)} NIM.</p><div className="split-inputs"><label>Return to employer<input inputMode="decimal" value={splits[signal.id]?.employer||""} onChange={event=>setSplits(value=>({...value,[signal.id]:{employer:event.target.value,employee:value[signal.id]?.employee||""}}))}/></label><label>Pay employee<input inputMode="decimal" value={splits[signal.id]?.employee||""} onChange={event=>setSplits(value=>({...value,[signal.id]:{employer:value[signal.id]?.employer||"",employee:event.target.value}}))}/></label><button className="primary" disabled={!!busy} onClick={()=>rule(signal)}>Confirm managed ruling</button></div></div></article>;
  if(signal.status==="ruling_pending"){const employer=BigInt(signal.ruling_employer_atomic||0),employee=BigInt(signal.ruling_employee_atomic||0);return <article key={signal.id} className="dispute-card"><div><small>FINAL RULING</small><h2>{signal.title}</h2><p>Complete every non-zero transfer below.</p></div><div className="ruling-panel">{employer>0n&&!signal.employer_settlement_hash&&<button className="primary" disabled={!!busy} onClick={()=>settle(signal,"employer",employer,signal.employer_wallet)}>Return {nim(employer).toFixed(5)} NIM to employer</button>}{employee>0n&&!signal.employee_settlement_hash&&<button className="primary" disabled={!!busy} onClick={()=>settle(signal,"employee",employee,signal.employee_wallet)}>Pay {nim(employee).toFixed(5)} NIM to employee</button>}</div></article>}
  const attentionPayment=signal.status==="attention_pending",pay=signal.status==="payout_pending",value=attentionPayment?attention:pay?remaining:signal.employee_wallet?remaining:total,recipient=attentionPayment||pay?signal.employee_wallet:signal.employer_wallet,outcome=attentionPayment?"employee":pay?"pay":"refund";return <article key={signal.id} className="dispute-card"><div><small>{attentionPayment?"ATTENTION FEE":pay?"DELIVERY PAYOUT":"REFUND"}</small><h2>{signal.title}</h2><p>{signal.sender_handle} → {signal.target_handle}</p><strong>{nim(value).toFixed(5)} NIM</strong></div><div className="ruling-panel"><code>{recipient}</code><button className="primary" disabled={!!busy} onClick={()=>settle(signal,outcome,value,recipient)}>{attentionPayment?"Release acceptance fee":pay?"Pay recipient with Nimiq Pay":"Refund employer"}</button></div></article>
 })}</div></section>
}
