"use client";
import {useState} from "react";
import {init} from "@nimiq/mini-app-sdk";

type Signal={id:string;title:string;sender_handle:string;target_handle:string;employer_wallet:string;employee_wallet:string;amount_atomic:string;status:"payout_pending"|"refund_pending"};type SdkError={error:{message:string}};const isError=(value:unknown):value is SdkError=>Boolean(value&&typeof value==="object"&&"error" in value);
async function authorize(){const provider=await init({timeout:10000}),accounts=await provider.listAccounts();if(isError(accounts))throw new Error(accounts.error.message);if(!accounts[0])throw new Error("Choose the Renda escrow account.");const challengeResponse=await fetch("/api/auth/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"challenge"})}),challenge=await challengeResponse.json() as{challengeId?:string;message?:string;error?:string};if(!challengeResponse.ok||!challenge.challengeId||!challenge.message)throw new Error(challenge.error||"Could not start authorization.");const signed=await provider.sign(challenge.message);if(isError(signed))throw new Error(signed.error.message);const response=await fetch("/api/auth/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"verify",challengeId:challenge.challengeId,address:accounts[0],publicKey:signed.publicKey,signature:signed.signature})}),result=await response.json();if(!response.ok)throw new Error(result.error||"This is not the Renda escrow account.");return provider}

export default function NimAdmin(){const[signals,setSignals]=useState<Signal[]>([]),[ready,setReady]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState("");async function load(){const response=await fetch("/api/signals/nimiq?admin=1"),result=await response.json();if(!response.ok)throw new Error(result.error||"Could not open the NIM settlement queue.");setSignals(result.signals)}async function open(){setNotice("");try{await authorize();await load();setReady(true)}catch(error){setNotice(error instanceof Error?error.message:"Could not authorize NIM administration.")}}async function settle(signal:Signal){setBusy(signal.id);setNotice("");try{const provider=await authorize(),outcome=signal.status==="payout_pending"?"pay":"refund",recipient=outcome==="pay"?signal.employee_wallet:signal.employer_wallet,value=Number(BigInt(signal.amount_atomic)),sent=await provider.sendBasicTransactionWithData({recipient,value,data:`RENDA-${outcome.toUpperCase()}:${signal.id}`});if(isError(sent))throw new Error(sent.error.message);let failure="The transaction is still confirming.";for(let attempt=0;attempt<8;attempt++){if(attempt)await new Promise(resolve=>setTimeout(resolve,2000));const response=await fetch("/api/signals/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,action:"settle",outcome,txHash:sent})}),result=await response.json();if(response.ok){failure="";break}failure=result.error||failure;if(!/confirmed|network/i.test(failure))break}if(failure)throw new Error(`${failure} Transaction: ${sent}`);await load()}catch(error){setNotice(error instanceof Error?error.message:"Could not settle this NIM request.")}finally{setBusy("")}}
 return <section className="arbitration-page nim-admin"><header><span className="eyebrow">MANAGED NIM CONSOLE</span><h1>Release held NIM.</h1><p>Only the Renda escrow account can open this queue and approve outgoing payouts or refunds in Nimiq Pay.</p>{!ready&&<button className="primary" onClick={open}>Authorize Renda escrow account</button>}</header>{notice&&<p className="inline-notice">{notice}</p>}{ready&&signals.length===0&&<div className="action-panel"><h3>No NIM settlements waiting</h3><p>Approved payouts and eligible refunds will appear here.</p></div>}<div className="nim-queue">{signals.map(signal=>{const pay=signal.status==="payout_pending",recipient=pay?signal.employee_wallet:signal.employer_wallet;return <article key={signal.id} className="dispute-card"><div><small>{pay?"PAYOUT":"REFUND"} · {signal.id.slice(0,8).toUpperCase()}</small><h2>{signal.title}</h2><p>{signal.sender_handle} → {signal.target_handle}</p><strong>{(Number(BigInt(signal.amount_atomic))/100000).toFixed(5)} NIM</strong></div><div className="ruling-panel"><small>SEND TO</small><code>{recipient}</code><p>{pay?"The employer approved the submitted work.":"This request qualified for a full refund."}</p><button className="primary" disabled={!!busy} onClick={()=>settle(signal)}>{busy===signal.id?"Confirming…":pay?"Pay recipient with Nimiq Pay":"Refund employer with Nimiq Pay"}</button></div></article>})}</div></section>}
