import {env} from "cloudflare:workers";
import {getCookie,readSession} from "@/lib/x-auth";
import {decodeEventLog,encodePacked,isAddressEqual,keccak256,stringToHex} from "viem";
import {escrowAbi,getPolygonConfig,polygonClient} from "@/lib/polygon";
import {ensureNimiqPaymentSchema,normalizeNimAddress} from "@/lib/nimiq-payments";
import {resolveXUser} from "@/lib/x-users";

const ADDRESS=/^0x[0-9a-fA-F]{40}$/;
const HANDLE=/^@[A-Za-z0-9_]{1,15}$/;
const TX=/^0x[0-9a-fA-F]{64}$/;

async function ensureSchema(db:D1Database){await db.batch([
  db.prepare("CREATE TABLE IF NOT EXISTS signals (id TEXT PRIMARY KEY, chain_id INTEGER NOT NULL DEFAULT 137, contract_request_id TEXT, sender_x_id TEXT NOT NULL, sender_handle TEXT NOT NULL, target_x_id TEXT NOT NULL, target_handle TEXT NOT NULL, employer_wallet TEXT NOT NULL, employee_wallet TEXT, title TEXT NOT NULL, terms TEXT NOT NULL, amount_atomic TEXT NOT NULL, attention_atomic TEXT NOT NULL, accept_by INTEGER NOT NULL, deliver_by INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'draft', funding_hash TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)"),
  db.prepare("CREATE INDEX IF NOT EXISTS signals_target_idx ON signals (target_x_id, created_at)"),
  db.prepare("CREATE INDEX IF NOT EXISTS signals_sender_idx ON signals (sender_x_id, created_at)"),
  db.prepare("CREATE INDEX IF NOT EXISTS signals_funding_idx ON signals (funding_hash)"),
]);await ensureNimiqPaymentSchema(db)}

function termsHash(record:Record<string,string|number>,title=String(record.title),terms=String(record.terms)){return keccak256(encodePacked(["string","string","string","uint256","uint256","uint64"],[String(record.target_handle).toLowerCase(),title,terms,BigInt(String(record.amount_atomic)),BigInt(String(record.attention_atomic)),BigInt(Number(record.deliver_by))]))}
function acceptedTermsHashes(record:Record<string,string|number>){const title=String(record.title).trim(),terms=String(record.terms).trim();const hashes=new Set<`0x${string}`>([termsHash(record,title,terms)]);for(const whitespace of [" ","\t","\n","\r\n"]){hashes.add(termsHash(record,`${title}${whitespace}`,terms));hashes.add(termsHash(record,title,`${whitespace}${terms}`));hashes.add(termsHash(record,`${whitespace}${title}`,terms));hashes.add(termsHash(record,title,`${terms}${whitespace}`))}return hashes}

export async function GET(request:Request){const db=(env as unknown as{DB?:D1Database}).DB;if(!db)return Response.json({error:"Signal storage is unavailable."},{status:503});await ensureSchema(db);const profile=await readSession(getCookie(request,"renda_x_session"));if(!profile)return Response.json({error:"Sign in with X to view signals."},{status:401});const sender=new URL(request.url).searchParams.get("role")==="sender",select="SELECT s.*,COALESCE(p.payment_mode,'polygon') payment_mode,p.payout_hash,p.refund_hash,w.cancel_requested_by FROM signals s LEFT JOIN signal_payment_profiles p ON p.signal_id=s.id LEFT JOIN nimiq_managed_workflows w ON w.signal_id=s.id";const rows=sender?await db.prepare(`${select} WHERE s.sender_x_id = ? ORDER BY s.created_at DESC LIMIT 100`).bind(profile.id).all<Record<string,string|number>>():await db.prepare(`${select} WHERE s.target_x_id = ? OR (s.target_x_id = '' AND lower(s.target_handle) = lower(?)) ORDER BY s.created_at DESC LIMIT 100`).bind(profile.id,`@${profile.username}`).all<Record<string,string|number>>();const now=Math.floor(Date.now()/1000),signals=rows.results.map(row=>String(row.status)==="funded"&&Number(row.accept_by)<now?{...row,status:"expired"}:row);return Response.json({signals})}

export async function POST(request:Request){const db=(env as unknown as{DB?:D1Database}).DB;if(!db)return Response.json({error:"Signal storage is unavailable."},{status:503});const profile=await readSession(getCookie(request,"renda_x_session"));if(!profile)return Response.json({error:"Sign in with X to create a signal."},{status:401});const body=await request.json() as Record<string,unknown>,paymentMode=body.paymentMode==="nim"?"nim":"polygon";const required=["targetHandle","employerWallet","title","terms","amountAtomic","attentionAtomic","acceptBy","deliverBy"];if(required.some(key=>body[key]===undefined||body[key]===""))return Response.json({error:"Complete all request fields."},{status:400});const requestedHandle=`@${String(body.targetHandle).trim().replace(/^@/,"").toLowerCase()}`;const employerWallet=String(body.employerWallet).trim(),validWallet=paymentMode==="nim"?normalizeNimAddress(employerWallet).length===36&&normalizeNimAddress(employerWallet).startsWith("NQ"):ADDRESS.test(employerWallet);if(!HANDLE.test(requestedHandle)||!validWallet)return Response.json({error:"Invalid recipient or wallet."},{status:400});let target:{id:string;username:string};try{target=await resolveXUser(requestedHandle.slice(1))}catch(error){if(paymentMode!=="nim")return Response.json({error:error instanceof Error?error.message:"X could not verify that recipient right now."},{status:503});target={id:"",username:requestedHandle.slice(1)}}const targetHandle=`@${target.username}`;const amount=BigInt(String(body.amountAtomic)),attention=BigInt(String(body.attentionAtomic));const acceptBy=Number(body.acceptBy),deliverBy=Number(body.deliverBy),now=Math.floor(Date.now()/1000);if(amount<=0n||attention<0n||attention>amount||!Number.isSafeInteger(acceptBy)||acceptBy>=deliverBy||deliverBy<now+48*60*60-60)return Response.json({error:"The reward is invalid or the deadline is less than 48 hours away."},{status:400});const title=String(body.title).trim().slice(0,100),terms=String(body.terms).trim().slice(0,4000);if(!title||!terms)return Response.json({error:"Title and terms are required."},{status:400});await ensureSchema(db);const id=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO signals (id, chain_id, sender_x_id, sender_handle, target_x_id, target_handle, employer_wallet, title, terms, amount_atomic, attention_atomic, accept_by, deliver_by, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'draft', ?, ?)").bind(id,paymentMode==="nim"?0:80002,profile.id,`@${profile.username}`,target.id,targetHandle,employerWallet,title,terms,amount.toString(),attention.toString(),acceptBy,deliverBy,now,now),db.prepare("INSERT INTO signal_payment_profiles (signal_id,payment_mode,created_at,updated_at) VALUES (?,?,?,?)").bind(id,paymentMode,now,now)]);return Response.json({id,status:"draft",paymentMode,normalized:{targetHandle,targetXId:target.id,title,terms}},{status:201})}

export async function PATCH(request:Request){const db=(env as unknown as{DB?:D1Database}).DB;if(!db)return Response.json({error:"Signal storage is unavailable."},{status:503});const profile=await readSession(getCookie(request,"renda_x_session"));if(!profile)return Response.json({error:"Sign in with X to confirm funding."},{status:401});const config=getPolygonConfig();if(!config)return Response.json({error:"Testnet escrow is not configured."},{status:503});const body=await request.json() as{id?:string;fundingHash?:`0x${string}`};if(!body.id||!TX.test(body.fundingHash||""))return Response.json({error:"A signal and transaction hash are required."},{status:400});await ensureSchema(db);const record=await db.prepare("SELECT * FROM signals WHERE id=? AND sender_x_id=?").bind(body.id,profile.id).first<Record<string,string|number>>();if(!record)return Response.json({error:"Signal not found."},{status:404});if(!["draft","funding_pending"].includes(String(record.status)))return Response.json({error:"This signal is not awaiting funding recovery."},{status:409});const duplicate=await db.prepare("SELECT id FROM signals WHERE funding_hash=? AND id<>? AND status<>'draft'").bind(body.fundingHash!.toLowerCase(),body.id).first();if(duplicate)return Response.json({error:"This transaction is already connected to another signal."},{status:409});
try{const client=polygonClient(config.rpcUrl);const receipt=await client.waitForTransactionReceipt({hash:body.fundingHash!});if(receipt.status!=="success"||!receipt.to||!isAddressEqual(receipt.to,config.escrowAddress))throw new Error("The escrow transaction was not successful.");let funded:{id:bigint;employer:`0x${string}`;targetIdentity:`0x${string}`;total:bigint}|undefined;for(const log of receipt.logs){if(!isAddressEqual(log.address,config.escrowAddress))continue;try{const decoded=decodeEventLog({abi:escrowAbi,data:log.data,topics:log.topics});if(decoded.eventName==="RequestFunded")funded=decoded.args}catch{}}const expectedTarget=keccak256(stringToHex(`x-user-id:${String(record.target_x_id)}`));if(!funded||!isAddressEqual(funded.employer,String(record.employer_wallet) as `0x${string}`)||funded.total!==BigInt(String(record.amount_atomic))||funded.targetIdentity!==expectedTarget)throw new Error("The transaction does not match this signal.");const onchain=await client.readContract({address:config.escrowAddress,abi:escrowAbi,functionName:"requests",args:[funded.id]});const baseMatches=isAddressEqual(onchain[0],String(record.employer_wallet) as `0x${string}`)&&isAddressEqual(onchain[2],config.arbitratorAddress)&&onchain[3]===BigInt(String(record.amount_atomic))&&onchain[4]===BigInt(String(record.attention_atomic))&&onchain[5]===BigInt(Number(record.accept_by))&&onchain[6]===BigInt(Number(record.deliver_by))&&onchain[7]===expectedTarget&&onchain[10]===1;if(!baseMatches)throw new Error("The on-chain request details do not match this signal.");const now=Math.floor(Date.now()/1000);await db.prepare("UPDATE signals SET chain_id=?,contract_request_id=?,status='funding_pending',funding_hash=?,updated_at=? WHERE id=?").bind(80002,funded.id.toString(),body.fundingHash!.toLowerCase(),now,body.id).run();if(!acceptedTermsHashes(record).has(onchain[8]))throw new Error("The transaction terms do not match this signal.");await db.prepare("UPDATE signals SET status='funded',updated_at=? WHERE id=?").bind(now,body.id).run();return Response.json({id:body.id,status:"funded",contractRequestId:funded.id.toString(),fundingHash:body.fundingHash})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not verify funding."},{status:400})}}
