"use client";
import {FormEvent,useEffect,useState} from "react";
import {init} from "@nimiq/mini-app-sdk";

type Signal={id:string;status:string;amount_atomic:string;employee_wallet?:string|null;accept_by?:number};
type Review={evidence:Array<{id:string;message:string;createdAt:number;attachments:Array<{name:string;url:string}>}>;messages:Array<{author_role:string;message:string;created_at:number}>};
type ErrorResult={error:{message:string}};
const isError=(value:unknown):value is ErrorResult=>Boolean(value&&typeof value==="object"&&"error" in value);

async function authenticateNimiq(){const provider=await init({timeout:10000}),accounts=await provider.listAccounts();if(isError(accounts))throw new Error(accounts.error.message);if(!accounts[0])throw new Error("Choose your Nimiq account first.");const challengeResponse=await fetch("/api/auth/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"challenge"})}),challenge=await challengeResponse.json() as{challengeId?:string;message?:string;error?:string};if(!challengeResponse.ok||!challenge.challengeId||!challenge.message)throw new Error(challenge.error||"Could not verify this Nimiq account.");const signed=await provider.sign(challenge.message);if(isError(signed))throw new Error(signed.error.message);const verified=await fetch("/api/auth/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"verify",challengeId:challenge.challengeId,address:accounts[0],publicKey:signed.publicKey,signature:signed.signature})}),result=await verified.json() as{identity?:{address:string};error?:string};if(!verified.ok||!result.identity)throw new Error(result.error||"Nimiq account verification failed.");return result.identity.address}

export function NimiqSignalActions({mode,signal,onDone}:{mode:"inbox"|"sent";signal:Signal;onDone:()=>Promise<void>}){
 const[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[review,setReview]=useState<Review>(),[revision,setRevision]=useState(""),[files,setFiles]=useState<string[]>([]),[fundingHash,setFundingHash]=useState("");
 async function refresh(){const response=await fetch(`/api/signals/workflow?signalId=${encodeURIComponent(signal.id)}`);if(response.ok)setReview(await response.json())}
 useEffect(()=>{void refresh()},[signal.id,signal.status]);
 async function action(name:"accept"|"approve"|"refund"){setBusy(name);setNotice("");try{if(name==="accept")await authenticateNimiq();const response=await fetch("/api/signals/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,action:name})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Could not update this NIM request.");await onDone()}catch(error){setNotice(error instanceof Error?error.message:"Could not update this NIM request.")}finally{setBusy("")}}
 async function workflow(name:"decline"|"revision"){setBusy(name);setNotice("");try{const response=await fetch("/api/signals/workflow",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signalId:signal.id,action:name,message:revision})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Could not update this request.");setRevision("");await onDone()}catch(error){setNotice(error instanceof Error?error.message:"Could not update this request.")}finally{setBusy("")}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element);setBusy("submit");setNotice("");try{const address=await authenticateNimiq();form.set("signalId",signal.id);form.set("wallet",address);const response=await fetch("/api/signals/evidence",{method:"POST",body:form}),result=await response.json();if(!response.ok)throw new Error(result.error||"Could not submit work.");element.reset();setFiles([]);await onDone()}catch(error){setNotice(error instanceof Error?error.message:"Could not submit work.")}finally{setBusy("")}}
 async function recover(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("recover");setNotice("");try{const response=await fetch("/api/signals/nimiq",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,action:"fund",txHash:fundingHash.trim()})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Could not verify this NIM payment.");setFundingHash("");await onDone()}catch(error){setNotice(error instanceof Error?error.message:"Could not verify this NIM payment.")}finally{setBusy("")}}
 const amount=(Number(BigInt(signal.amount_atomic))/100000).toFixed(5);
 return <div className="workflow-actions nim-workflow">
  {mode==="sent"&&signal.status==="draft"&&<form className="recovery-panel" onSubmit={recover}><span>NIM FUNDING RECOVERY</span><h3>Payment still confirming?</h3><p>Paste the transaction hash returned by Nimiq Pay. Renda will verify the sender, amount, escrow address and request reference.</p><input value={fundingHash} onChange={event=>setFundingHash(event.target.value)} placeholder="Nimiq transaction hash" pattern="[0-9a-fA-F]{64}" required/><button className="primary" disabled={!!busy}>{busy==="recover"?"Checking…":"Verify NIM funding"}</button></form>}
  {mode==="inbox"&&signal.status==="funded"&&<section className="action-panel"><small>MANAGED NIM REQUEST</small><h3>Accept this funded request</h3><p>Nimiq Pay will verify the account that should receive {amount} NIM after approved delivery.</p><div><button className="primary" disabled={!!busy} onClick={()=>action("accept")}>{busy==="accept"?"Verifying…":"Accept with Nimiq Pay"}</button><button className="secondary" disabled={!!busy} onClick={()=>workflow("decline")}>Decline</button></div></section>}
  {mode==="inbox"&&["accepted","revision_requested"].includes(signal.status)&&<form className="delivery-form" onSubmit={submit}><h3>{signal.status==="revision_requested"?"Send your revision":"Deliver your work"}</h3>{signal.status==="revision_requested"&&review?.messages.at(-1)&&<p className="revision-note"><strong>Employer feedback:</strong> {review.messages.at(-1)!.message}</p>}<p>Add your message, links and supporting attachments. Your Nimiq account is verified when you submit.</p><label>Message<textarea name="message" rows={5} placeholder="Explain what you completed and paste any links here…"/></label><div className="attachment-row"><label className="attachment-button">📎 <strong>Add attachments</strong><input name="files" type="file" accept="image/*,video/*,audio/*,.pdf,.txt" multiple onChange={e=>setFiles(Array.from(e.currentTarget.files||[],file=>file.name))}/></label><span className="attachment-help">Images, video, audio or documents</span></div>{files.length>0&&<ul className="attachment-list">{files.map((name,index)=><li key={`${name}-${index}`}>📄 {name}</li>)}</ul>}<button className="primary" disabled={!!busy}>{busy==="submit"?"Submitting…":"Submit completed work"}</button></form>}
  {(review?.evidence||[]).length>0&&<section className="submission-review"><small>SUBMISSION HISTORY</small>{(review?.evidence||[]).map((item,index)=><article key={item.id}><div><strong>Submission {index+1}</strong><time>{new Date(item.createdAt*1000).toLocaleString()}</time></div>{item.message&&<p>{item.message}</p>}{item.attachments.map(file=><a key={file.url} href={file.url} target="_blank" rel="noreferrer">📎 {file.name}</a>)}</article>)}</section>}
  {mode==="sent"&&signal.status==="submitted"&&<section className="review-actions"><h3>Review submitted work</h3><p>Approval places the full {amount} NIM payout in your Renda admin queue.</p><button className="primary" disabled={!!busy} onClick={()=>action("approve")}>{busy==="approve"?"Approving…":"Approve NIM payout"}</button><label>Revision feedback<textarea rows={3} value={revision} onChange={e=>setRevision(e.target.value)} placeholder="Explain what needs to change…"/></label><button className="secondary" disabled={!!busy||!revision.trim()} onClick={()=>workflow("revision")}>Request revision</button></section>}
  {mode==="sent"&&["expired","declined"].includes(signal.status)&&<section className="action-panel expired-panel"><h3>Request a managed refund</h3><p>The Renda escrow administrator will return the full {amount} NIM to the funding account.</p><button className="primary" disabled={!!busy} onClick={()=>action("refund")}>{busy==="refund"?"Requesting…":"Add refund to admin queue"}</button></section>}
  {["payout_pending","refund_pending"].includes(signal.status)&&<section className="action-panel nim-pending"><small>ADMIN APPROVAL REQUIRED</small><h3>{signal.status==="payout_pending"?"Payout queued":"Refund queued"}</h3><p>The funds remain in Renda’s managed account until the escrow administrator confirms the outgoing NIM transaction.</p></section>}
  {notice&&<p className="inline-notice">{notice}</p>}
 </div>
}
