"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type ApiSignal={id:string;sender_handle:string;target_handle:string;title:string;terms:string;amount_atomic:string;attention_atomic:string;deliver_by:number;status:string;funding_hash?:string|null};
const labels:Record<string,string>={draft:"Draft",funded:"Waiting for recipient",accepted:"In progress",submitted:"Under review",paid:"Paid",disputed:"In arbitration"};
const amount=(atomic:string)=>Number(BigInt(atomic))/1_000_000;
const date=(seconds:number)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(seconds*1000));

export function SignalWorkspace({mode}:{mode:"inbox"|"sent"}){
  const[items,setItems]=useState<ApiSignal[]>([]);const[selectedId,setSelectedId]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{let active=true;setLoading(true);fetch(`/api/signals?role=${mode==="sent"?"sender":"target"}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load signals.");return data.signals as ApiSignal[]}).then(rows=>{if(active){setItems(rows);setSelectedId(rows[0]?.id||"")}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[mode]);
  const selected=useMemo(()=>items.find(s=>s.id===selectedId)||items[0],[items,selectedId]);
  if(loading)return <section className="app-empty"><span className="eyebrow">LOADING SIGNALS</span><h1>Checking for funded requests…</h1></section>;
  if(error)return <section className="app-empty"><span className="eyebrow">COULD NOT LOAD</span><h1>Your signals are unavailable.</h1><p>{error}</p></section>;
  if(!selected)return <section className="app-empty"><span className="eyebrow">{mode==="inbox"?"DIRECTED AT YOU":"CREATED BY YOU"}</span><h1>{mode==="inbox"?"No signals yet.":"You haven’t sent a signal yet."}</h1><p>{mode==="inbox"?"Requests addressed to your verified X account will appear here.":"Create a request and it will appear here as a draft until its on-chain funding is confirmed."}</p>{mode==="sent"&&<Link className="cta lime" href="/x/new">Create a signal <span>→</span></Link>}</section>;
  const total=amount(selected.amount_atomic),attention=amount(selected.attention_atomic);
  return <section className="workspace"><aside className="request-list"><div className="list-heading"><span className="eyebrow">{mode==="inbox"?"DIRECTED AT YOU":"CREATED BY YOU"}</span><h1>{mode==="inbox"?"Your attention has value.":"Signals you sent."}</h1><p>{mode==="inbox"?"Verified requests addressed to your X account.":"Real records from your connected X identity."}</p></div><div className="list-items">{items.map(item=><button key={item.id} className={`request-row ${selected.id===item.id?"selected":""}`} onClick={()=>setSelectedId(item.id)}><span className={`state-dot ${item.status}`}/><span className="row-copy"><small>{mode==="inbox"?item.sender_handle:item.target_handle}</small><strong>{item.title}</strong><em>{labels[item.status]||item.status} · {date(item.deliver_by)}</em></span><span className="row-amount"><strong>${amount(item.amount_atomic).toFixed(2)}</strong><small>USDT</small></span></button>)}</div></aside><article className="request-detail"><div className="detail-top"><span>{selected.id.slice(0,8).toUpperCase()}</span><span className={`status-pill ${selected.status}`}>{labels[selected.status]||selected.status}</span></div><div className="people-line"><span className="avatar">{selected.sender_handle.slice(1,2).toUpperCase()}</span><div><small>FROM</small><strong>{selected.sender_handle}</strong></div><span className="arrow">→</span><span className="avatar target">{selected.target_handle.slice(1,2).toUpperCase()}</span><div><small>FOR</small><strong>{selected.target_handle}</strong></div></div><h2>{selected.title}</h2><p className="brief">{selected.terms}</p><div className="money-card"><div><small>TOTAL REQUESTED</small><strong>{total.toFixed(2)} <span>USDT</span></strong></div><div><small>ATTENTION FEE</small><strong>{attention.toFixed(2)} <span>USDT</span></strong></div><div><small>DELIVERY REWARD</small><strong>{(total-attention).toFixed(2)} <span>USDT</span></strong></div></div><div className="terms"><div><small>DELIVER BY</small><strong>{date(selected.deliver_by)}</strong></div><div><small>NETWORK</small><strong>Polygon</strong></div><div><small>FUNDING</small><strong>{selected.funding_hash?"Confirmed on-chain":"Not yet confirmed"}</strong></div></div>{selected.status==="draft"&&<div className="action-panel"><h3>This is a saved draft.</h3><p>No payment is locked yet. On-chain funding will activate this request once the escrow integration confirms its transaction.</p></div>}</article></section>;
}
