"use client";
import {FormEvent,useEffect,useState} from "react";
import {createPublicClient,createWalletClient,custom,http,parseAbi} from "viem";
import {polygonAmoy} from "viem/chains";
const escrowAbi=parseAbi(["function acceptRequest(uint256 id,uint64 authorizationExpiry,bytes32 nonce,bytes signature)","function submitEvidence(uint256 id,bytes32 evidenceHash)","function proposeSettlement(uint256 id,uint256 employerAmount,uint256 employeeAmount)","function acceptSettlement(uint256 id)","function openDispute(uint256 id)"]);
type Provider={request(args:{method:string;params?:unknown[]}):Promise<unknown>};
type Signal={id:string;title?:string;status:string;contract_request_id?:string|null;amount_atomic:string;attention_atomic:string;employee_wallet?:string|null};
type Config={configured:boolean;rpcUrl:string;escrowAddress:`0x${string}`};
export function SignalActions({mode,signal,onDone}:{mode:"inbox"|"sent";signal:Signal;onDone:()=>Promise<void>}){const[config,setConfig]=useState<Config>(),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");useEffect(()=>{fetch("/api/polygon/config").then(r=>r.json()).then(setConfig)},[]);
async function clients(){const provider=(window as unknown as{ethereum?:Provider}).ethereum;if(!provider||!config?.escrowAddress)throw new Error("Connect a Polygon wallet first.");const accounts=await provider.request({method:"eth_requestAccounts"}) as `0x${string}`[];const account=accounts[0];if(!account)throw new Error("No wallet selected.");try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x13882"}]})}catch(switchError){const code=(switchError as {code?:number}).code;if(code===4902){await provider.request({method:"wallet_addEthereumChain",params:[{chainId:"0x13882",chainName:"Polygon Amoy",nativeCurrency:{name:"POL",symbol:"POL",decimals:18},rpcUrls:[config.rpcUrl],blockExplorerUrls:["https://amoy.polygonscan.com"]}]});await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x13882"}]})}else throw new Error("Switch your wallet to Polygon Amoy to continue.")}const currentChain=await provider.request({method:"eth_chainId"}) as string;if(Number.parseInt(currentChain,16)!==80002)throw new Error("Your wallet is still on another network. Switch to Polygon Amoy and try again.");return{account,wallet:createWalletClient({account,chain:polygonAmoy,transport:custom(provider)}),client:createPublicClient({chain:polygonAmoy,transport:http(config.rpcUrl)})}}
async function record(action:string,txHash:`0x${string}`,wallet:string){const r=await fetch("/api/signals/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,action,txHash,wallet})}),data=await r.json();if(!r.ok)throw new Error(data.error||"Could not verify the action.");await onDone()}
async function accept(){setBusy("accept");setNotice("");try{const{account,wallet,client}=await clients(),authResponse=await fetch("/api/signals/accept",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,wallet:account})}),auth=await authResponse.json();if(!authResponse.ok)throw new Error(auth.error||"Could not authorize this X account.");const hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"acceptRequest",args:[BigInt(auth.contractId),BigInt(auth.authorizationExpiry),auth.nonce,auth.signature]});await client.waitForTransactionReceipt({hash});await record("accept",hash,account)}catch(e){setNotice(e instanceof Error?e.message:"Could not accept request.")}finally{setBusy("")}}
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("submit");setNotice("");try{const{account,wallet,client}=await clients(),form=new FormData(event.currentTarget);form.set("signalId",signal.id);form.set("wallet",account);const uploaded=await fetch("/api/signals/evidence",{method:"POST",body:form}),data=await uploaded.json();if(!uploaded.ok)throw new Error(data.error||"Could not upload the submission.");const hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"submitEvidence",args:[BigInt(signal.contract_request_id!),data.contentHash]});await client.waitForTransactionReceipt({hash});await record("submit",hash,account)}catch(e){setNotice(e instanceof Error?e.message:"Could not submit work.")}finally{setBusy("")}}
async function cancel(action:"request_cancel"|"accept_cancel"|"dispute"){setBusy(action);setNotice("");try{const{account,wallet,client}=await clients(),id=BigInt(signal.contract_request_id!);let hash:`0x${string}`;if(action==="request_cancel"){const remaining=BigInt(signal.amount_atomic)-BigInt(signal.attention_atomic);hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"proposeSettlement",args:[id,remaining,0n]})}else if(action==="accept_cancel")hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"acceptSettlement",args:[id]});else hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"openDispute",args:[id]});await client.waitForTransactionReceipt({hash});await record(action,hash,account)}catch(e){setNotice(e instanceof Error?e.message:"Could not complete this action.")}finally{setBusy("")}}
if(!signal.contract_request_id)return null;return <div className="workflow-actions">{mode==="inbox"&&signal.status==="funded"&&<div className="action-panel"><h3>Accept this request</h3><p>Your connected wallet will receive the attention fee and become the only wallet allowed to deliver the work.</p><button className="primary" disabled={!!busy} onClick={accept}>{busy==="accept"?"Accepting…":"Accept funded request"}</button></div>}{mode==="inbox"&&signal.status==="accepted"&&<form className="delivery-form" onSubmit={submit}><h3>Deliver your work</h3><p>Add any combination of a message, links and files required by the request.</p><label>Message<textarea name="message" rows={4} placeholder="Explain what you completed…"/></label><label>Links<textarea name="links" rows={2} placeholder="One HTTPS link per line" onChange={e=>{const form=e.currentTarget.form;if(!form)return;form.querySelectorAll('input[data-link]').forEach(n=>n.remove());e.currentTarget.value.split(/\n/).map(v=>v.trim()).filter(Boolean).forEach(value=>{const input=document.createElement('input');input.type='hidden';input.name='links';input.value=value;input.dataset.link='true';form.appendChild(input)})}}/></label><label className="upload-box">Images, video, audio or documents<input name="files" type="file" accept="image/*,video/*,audio/*,.pdf,.txt" multiple/></label><button className="primary" disabled={!!busy}>{busy==="submit"?"Submitting…":"Submit work on-chain"}</button></form>}{["accepted","submitted"].includes(signal.status)&&<div className="cancel-panel"><h3>Need to cancel?</h3><p>Mutual cancellation returns every token still in escrow to the employer. There is no custom split.</p><button className="secondary" disabled={!!busy} onClick={()=>cancel("request_cancel")}>{busy==="request_cancel"?"Requesting…":"Request mutual cancellation"}</button></div>}{signal.status==="cancel_requested"&&<div className="cancel-panel"><h3>Cancellation requested</h3><p>Accept to return all remaining escrow to the employer. If you disagree, open a dispute.</p><div><button className="primary" disabled={!!busy} onClick={()=>cancel("accept_cancel")}>Accept cancellation</button><button className="secondary dispute" disabled={!!busy} onClick={()=>cancel("dispute")}>Decline & open dispute</button></div></div>}{notice&&<p className="inline-notice">{notice}</p>}</div>}
