"use client";
import {FormEvent,useEffect,useState} from "react";
import {createPublicClient,createWalletClient,custom,http,parseAbi} from "viem";
import {polygonAmoy} from "viem/chains";
const escrowAbi=parseAbi(["function acceptRequest(uint256 id,uint64 authorizationExpiry,bytes32 nonce,bytes signature)","function submitEvidence(uint256 id,bytes32 evidenceHash)","function approve(uint256 id)","function reclaimUnaccepted(uint256 id)","function proposeSettlement(uint256 id,uint256 employerAmount,uint256 employeeAmount)","function acceptSettlement(uint256 id)","function openDispute(uint256 id)"]);
type Provider={request(args:{method:string;params?:unknown[]}):Promise<unknown>};
type Signal={id:string;status:string;contract_request_id?:string|null;amount_atomic:string;attention_atomic:string;accept_by?:number;employee_wallet?:string|null};
type Review={evidence:Array<{id:string;message:string;createdAt:number;attachments:Array<{name:string;url:string}>}>;messages:Array<{author_role:string;message:string;created_at:number}>};
type Config={configured:boolean;rpcUrl:string;escrowAddress:`0x${string}`};
export function SignalActions({mode,signal,onDone}:{mode:"inbox"|"sent";signal:Signal;onDone:()=>Promise<void>}){
 const[config,setConfig]=useState<Config>(),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[attachments,setAttachments]=useState<string[]>([]),[review,setReview]=useState<Review>(),[revision,setRevision]=useState("");
 useEffect(()=>{fetch("/api/polygon/config").then(r=>r.json()).then(setConfig)},[]);
 useEffect(()=>{if(["submitted","revision_requested","paid","disputed"].includes(signal.status))fetch(`/api/signals/workflow?signalId=${encodeURIComponent(signal.id)}`).then(r=>r.json()).then(setReview)},[signal.id,signal.status]);
 async function clients(){const provider=(window as unknown as{ethereum?:Provider}).ethereum;if(!provider||!config?.escrowAddress)throw new Error("Connect a Polygon wallet first.");const accounts=await provider.request({method:"eth_requestAccounts"}) as `0x${string}`[];const account=accounts[0];if(!account)throw new Error("No wallet selected.");try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x13882"}]})}catch(switchError){if((switchError as{code?:number}).code!==4902)throw new Error("Switch your wallet to Polygon Amoy to continue.");await provider.request({method:"wallet_addEthereumChain",params:[{chainId:"0x13882",chainName:"Polygon Amoy",nativeCurrency:{name:"POL",symbol:"POL",decimals:18},rpcUrls:[config.rpcUrl],blockExplorerUrls:["https://amoy.polygonscan.com"]}]});await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x13882"}]})}const currentChain=await provider.request({method:"eth_chainId"}) as string;if(Number.parseInt(currentChain,16)!==80002)throw new Error("Your wallet is still on another network. Switch to Polygon Amoy and try again.");return{account,wallet:createWalletClient({account,chain:polygonAmoy,transport:custom(provider)}),client:createPublicClient({chain:polygonAmoy,transport:http(config.rpcUrl)})}}
 async function record(action:string,txHash:`0x${string}`,wallet:string){const r=await fetch("/api/signals/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,action,txHash,wallet})}),data=await r.json();if(!r.ok)throw new Error(data.error||"Could not verify the action.");await onDone()}
 async function accept(){setBusy("accept");setNotice("");try{const{account,wallet,client}=await clients(),authResponse=await fetch("/api/signals/accept",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:signal.id,wallet:account})}),auth=await authResponse.json();if(!authResponse.ok)throw new Error(auth.error||"Could not authorize this X account.");const hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"acceptRequest",args:[BigInt(auth.contractId),BigInt(auth.authorizationExpiry),auth.nonce,auth.signature]});await client.waitForTransactionReceipt({hash});await record("accept",hash,account)}catch(e){setNotice(e instanceof Error?e.message:"Could not accept request.")}finally{setBusy("")}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy("submit");setNotice("");try{const{account,wallet,client}=await clients();form.set("signalId",signal.id);form.set("wallet",account);const uploaded=await fetch("/api/signals/evidence",{method:"POST",body:form}),data=await uploaded.json();if(!uploaded.ok)throw new Error(data.error||"Could not upload the submission.");if(data.needsChain){const hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"submitEvidence",args:[BigInt(signal.contract_request_id!),data.contentHash]});await client.waitForTransactionReceipt({hash});await record("submit",hash,account)}else await onDone()}catch(e){setNotice(e instanceof Error?e.message:"Could not submit work.")}finally{setBusy("")}}
 async function workflow(action:"decline"|"revision"){setBusy(action);setNotice("");try{const r=await fetch("/api/signals/workflow",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signalId:signal.id,action,message:revision})}),data=await r.json();if(!r.ok)throw new Error(data.error||"Could not update this request.");setRevision("");await onDone()}catch(e){setNotice(e instanceof Error?e.message:"Could not update this request.")}finally{setBusy("")}}
 async function settle(action:"approve"|"reclaim"){setBusy(action);setNotice("");try{const{account,wallet,client}=await clients(),hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:action==="approve"?"approve":"reclaimUnaccepted",args:[BigInt(signal.contract_request_id!)]});await client.waitForTransactionReceipt({hash});await record(action,hash,account)}catch(e){setNotice(e instanceof Error?e.message:"Could not complete payment.")}finally{setBusy("")}}
 async function cancel(action:"request_cancel"|"accept_cancel"|"dispute"){setBusy(action);setNotice("");try{const{account,wallet,client}=await clients(),id=BigInt(signal.contract_request_id!);let hash:`0x${string}`;if(action==="request_cancel"){const remaining=BigInt(signal.amount_atomic)-BigInt(signal.attention_atomic);hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"proposeSettlement",args:[id,remaining,0n]})}else if(action==="accept_cancel")hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"acceptSettlement",args:[id]});else hash=await wallet.writeContract({address:config!.escrowAddress,abi:escrowAbi,functionName:"openDispute",args:[id]});await client.waitForTransactionReceipt({hash});await record(action,hash,account)}catch(e){setNotice(e instanceof Error?e.message:"Could not complete this action.")}finally{setBusy("")}}
 if(!signal.contract_request_id)return null;
 const deliveryForm=<form className="delivery-form" onSubmit={submit}><h3>{signal.status==="revision_requested"?"Send your revision":"Deliver your work"}</h3>{signal.status==="revision_requested"&&review?.messages.at(-1)&&<p className="revision-note"><strong>Employer feedback:</strong> {review.messages.at(-1)!.message}</p>}<p>Write your update below. Paste links directly into the message and attach supporting files.</p><label>Message<textarea name="message" rows={5} placeholder="Explain what you completed and paste any links here…"/></label><div className="attachment-row"><label className="attachment-button" title="Add attachments"><span aria-hidden="true">📎</span><strong>Add attachments</strong><input name="files" type="file" accept="image/*,video/*,audio/*,.pdf,.txt" multiple onChange={e=>setAttachments(Array.from(e.currentTarget.files||[],file=>file.name))}/></label><span className="attachment-help">Images, video, audio or documents</span></div>{attachments.length>0&&<ul className="attachment-list">{attachments.map((name,index)=><li key={`${name}-${index}`}><span aria-hidden="true">📄</span>{name}</li>)}</ul>}<button className="primary" disabled={!!busy}>{busy==="submit"?"Submitting…":signal.status==="revision_requested"?"Send revised work":"Submit work on-chain"}</button></form>;
 return <div className="workflow-actions">
  {mode==="inbox"&&signal.status==="funded"&&<div className="action-panel"><h3>Respond to this request</h3><p>Accepting pays the attention fee and assigns this task to your wallet. Declining rejects only this request.</p><div><button className="primary" disabled={!!busy} onClick={accept}>{busy==="accept"?"Accepting…":"Accept request"}</button><button className="secondary" disabled={!!busy} onClick={()=>workflow("decline")}>{busy==="decline"?"Declining…":"Decline request"}</button></div></div>}
  {mode==="inbox"&&["accepted","revision_requested"].includes(signal.status)&&deliveryForm}
  {review?.evidence?.length>0&&<section className="submission-review"><small>SUBMISSION HISTORY</small>{review.evidence.map((item,index)=><article key={item.id}><div><strong>Submission {index+1}</strong><time>{new Date(item.createdAt*1000).toLocaleString()}</time></div>{item.message&&<p>{item.message}</p>}{item.attachments.length>0&&<div className="review-files">{item.attachments.map(file=><a key={file.url} href={file.url} target="_blank" rel="noreferrer">📎 {file.name}</a>)}</div>}</article>)}</section>}
  {mode==="sent"&&signal.status==="submitted"&&<div className="review-actions"><h3>Review submitted work</h3><p>Approve to release the delivery reward, request a revision with clear feedback, or open a dispute.</p><button className="primary" disabled={!!busy} onClick={()=>settle("approve")}>{busy==="approve"?"Releasing payment…":"Approve & release payment"}</button><label>Revision feedback<textarea rows={3} value={revision} onChange={e=>setRevision(e.target.value)} placeholder="Explain exactly what needs to change…"/></label><button className="secondary" disabled={!!busy||!revision.trim()} onClick={()=>workflow("revision")}>Request revision</button><button className="secondary dispute" disabled={!!busy} onClick={()=>cancel("dispute")}>Open dispute</button></div>}
  {mode==="sent"&&signal.status==="revision_requested"&&<div className="action-panel"><h3>Revision requested</h3><p>The recipient can see your feedback and submit replacement evidence.</p></div>}
  {mode==="sent"&&signal.status==="declined"&&<div className="action-panel"><h3>Request declined</h3><p>{signal.accept_by&&Date.now()/1000>signal.accept_by?"The acceptance deadline has passed. Reclaim the full funded amount now.":`The full funded amount becomes reclaimable after ${signal.accept_by?new Date(signal.accept_by*1000).toLocaleString():"the acceptance deadline"}.`}</p>{signal.accept_by&&Date.now()/1000>signal.accept_by&&<button className="primary" disabled={!!busy} onClick={()=>settle("reclaim")}>Reclaim full funding</button>}</div>}
  {["accepted","submitted"].includes(signal.status)&&<div className="cancel-panel"><h3>Need to cancel?</h3><p>Mutual cancellation returns every token still in escrow to the employer. There is no custom split.</p><button className="secondary" disabled={!!busy} onClick={()=>cancel("request_cancel")}>{busy==="request_cancel"?"Requesting…":"Request mutual cancellation"}</button></div>}
  {signal.status==="cancel_requested"&&<div className="cancel-panel"><h3>Cancellation requested</h3><p>Accept to return all remaining escrow to the employer. If you disagree, open a dispute.</p><div><button className="primary" disabled={!!busy} onClick={()=>cancel("accept_cancel")}>Accept cancellation</button><button className="secondary dispute" disabled={!!busy} onClick={()=>cancel("dispute")}>Decline & open dispute</button></div></div>}
  {notice&&<p className="inline-notice">{notice}</p>}
 </div>
}
