"use client";
import {useEffect,useState} from "react";
import {createPublicClient,createWalletClient,custom,encodeDeployData,http,type Abi} from "viem";
import {polygonAmoy} from "viem/chains";

type Config={configured:boolean;contractVersion?:string;rpcUrl:string;explorerUrl:string;arbitratorAddress?:`0x${string}`;identitySignerAddress?:`0x${string}`;tokenAddress?:`0x${string}`;escrowAddress?:`0x${string}`};
type Artifact={abi:Abi;bytecode:`0x${string}`};
type Artifacts={TestUSDT:Artifact;RendaSignalEscrow:Artifact};
type Provider={request(args:{method:string;params?:unknown[]}):Promise<unknown>};
export default function SetupPage(){const[config,setConfig]=useState<Config>();const[status,setStatus]=useState("");const[token,setToken]=useState<`0x${string}`>();const[escrow,setEscrow]=useState<`0x${string}`>();const[busy,setBusy]=useState(false);
useEffect(()=>{fetch("/api/polygon/config").then(r=>r.json()).then(data=>{setConfig(data);if(data.tokenAddress)setToken(data.tokenAddress)})},[]);
async function deploy(){setBusy(true);try{if(!config?.arbitratorAddress||!config.identitySignerAddress)throw new Error("Deployment identities are missing.");const provider=(window as unknown as{ethereum?:Provider}).ethereum;if(!provider)throw new Error("Open this page inside Nimiq Pay, MetaMask, or Rabby.");const accounts=await provider.request({method:"eth_requestAccounts"}) as `0x${string}`[];const account=accounts[0];if(!account||account.toLowerCase()!==config.arbitratorAddress.toLowerCase())throw new Error("Connect the configured deployment wallet.");try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x13882"}]})}catch{await provider.request({method:"wallet_addEthereumChain",params:[{chainId:"0x13882",chainName:"Polygon Amoy",nativeCurrency:{name:"POL",symbol:"POL",decimals:18},rpcUrls:[config.rpcUrl],blockExplorerUrls:[config.explorerUrl]}]})}const artifacts=await fetch("/contracts.json").then(r=>r.json()) as Artifacts;const wallet=createWalletClient({account,chain:polygonAmoy,transport:custom(provider)});const client=createPublicClient({chain:polygonAmoy,transport:http(config.rpcUrl)});const fees=await client.estimateFeesPerGas();const feeFields=fees.maxFeePerGas&&fees.maxPriorityFeePerGas?{maxFeePerGas:fees.maxFeePerGas,maxPriorityFeePerGas:fees.maxPriorityFeePerGas}:{};let tokenAddress=token;if(!tokenAddress){const tokenData=encodeDeployData({abi:artifacts.TestUSDT.abi,bytecode:artifacts.TestUSDT.bytecode});const tokenGas=await client.estimateGas({account,data:tokenData});setStatus("Confirm deployment of the valueless tUSDT test token in your wallet.");const tokenHash=await wallet.deployContract({abi:artifacts.TestUSDT.abi,bytecode:artifacts.TestUSDT.bytecode,gas:tokenGas*120n/100n,...feeFields});const tokenReceipt=await client.waitForTransactionReceipt({hash:tokenHash});if(!tokenReceipt.contractAddress)throw new Error("Test token deployment did not return an address.");tokenAddress=tokenReceipt.contractAddress;setToken(tokenAddress)}const escrowArgs=[tokenAddress,config.identitySignerAddress] as const;const escrowData=encodeDeployData({abi:artifacts.RendaSignalEscrow.abi,bytecode:artifacts.RendaSignalEscrow.bytecode,args:escrowArgs});const escrowGas=await client.estimateGas({account,data:escrowData});setStatus("Confirm deployment of the Renda escrow contract in your wallet.");const escrowHash=await wallet.deployContract({abi:artifacts.RendaSignalEscrow.abi,bytecode:artifacts.RendaSignalEscrow.bytecode,args:escrowArgs,gas:escrowGas*120n/100n,...feeFields});const escrowReceipt=await client.waitForTransactionReceipt({hash:escrowHash});if(!escrowReceipt.contractAddress)throw new Error("Escrow deployment did not return an address.");setEscrow(escrowReceipt.contractAddress);setStatus("Both contracts are live on Amoy. Copy the two public addresses below.")}catch(error){setStatus(error instanceof Error?error.message:"Deployment failed.")}finally{setBusy(false)}}
if(config?.configured&&config.contractVersion==="2")return <section className="app-empty"><span className="eyebrow">AMOY V2 READY</span><h1>Upgraded contracts are configured.</h1><p>Test token: {config.tokenAddress}<br/>Escrow: {config.escrowAddress}</p></section>;
return <section className="app-empty setup-page"><span className="eyebrow">ESCROW V2 UPGRADE</span><h1>Deploy the upgraded escrow.</h1><p>{token?"The test token is already deployed and will be reused. Your wallet will show one escrow deployment confirmation.":"This uses Amoy test POL and creates a valueless tUSDT token plus the upgraded escrow. Your wallet will show two separate confirmations."} Nothing can be deployed without your approval.</p><div className="deployment-facts"><div><small>DEPLOYER / ARBITRATOR</small><strong>{config?.arbitratorAddress||"Loading…"}</strong></div><div><small>IDENTITY SIGNER</small><strong>{config?.identitySignerAddress||"Loading…"}</strong></div></div><button className="primary" disabled={busy||!config?.identitySignerAddress} onClick={deploy}>{busy?"Deployment in progress…":token?"Deploy upgraded escrow":"Deploy both contracts"}</button>{status&&<p className="inline-notice">{status}</p>}{token&&<div className="contract-result"><small>TEST TOKEN ADDRESS</small><code>{token}</code></div>}{escrow&&<div className="contract-result"><small>NEW ESCROW ADDRESS</small><code>{escrow}</code></div>}</section>}
