"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
type Signal={id:string;sender_handle:string;target_handle:string;title:string;terms:string;amount_atomic:string;attention_atomic:string;deliver_by:number;status:string};
const money=(value:string)=>Number(BigInt(value))/1_000_000;
const due=(seconds:number)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(seconds*1000));
const wrap=(c:CanvasRenderingContext2D,text:string,x:number,y:number,max:number,lineHeight:number,maxLines=3)=>{const words=text.split(/\s+/);let line="",row=0;for(const word of words){const next=`${line} ${word}`.trim();if(c.measureText(next).width>max&&line){c.fillText(line,x,y+row*lineHeight);row++;line=word;if(row===maxLines-1)break}else line=next}if(line&&row<maxLines)c.fillText(line,x,y+row*lineHeight)};
async function makeCard(signal:Signal){const canvas=document.createElement("canvas");canvas.width=1200;canvas.height=675;const c=canvas.getContext("2d");if(!c)throw new Error("This browser cannot create the offer card.");c.fillStyle="#0a0b09";c.fillRect(0,0,1200,675);c.fillStyle="#d9ff36";c.fillRect(0,0,18,675);c.font="900 24px Arial";c.fillStyle="#f3f2eb";c.fillText("RENDA SIGNAL",70,72);c.font="800 16px Arial";c.fillStyle="#7856ff";c.fillText(`FUNDED REQUEST FOR ${signal.target_handle.toUpperCase()}`,70,142);c.font="700 60px Arial";c.fillStyle="#ffffff";wrap(c,signal.title,70,225,1040,68,3);c.font="400 24px Arial";c.fillStyle="#a8aaa2";wrap(c,signal.terms,70,432,1040,34,2);const total=money(signal.amount_atomic),attention=money(signal.attention_atomic);c.fillStyle="#171814";c.fillRect(70,520,1060,105);c.font="800 14px Arial";c.fillStyle="#8b8d85";c.fillText("TOTAL LOCKED",100,553);c.fillText("DELIVERY REWARD",370,553);c.fillText("DELIVER BY",710,553);c.font="900 28px Arial";c.fillStyle="#d9ff36";c.fillText(`${total.toFixed(2)} tUSDT`,100,594);c.fillStyle="#ffffff";c.fillText(`${(total-attention).toFixed(2)} tUSDT`,370,594);c.font="700 20px Arial";c.fillText(due(signal.deliver_by),710,592);c.font="700 13px Arial";c.fillStyle="#7856ff";c.fillText("FUNDED ON POLYGON AMOY",925,70);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/png"));if(!blob)throw new Error("Could not create the offer card.");return new File([blob],`renda-signal-${signal.id.slice(0,8)}.png`,{type:"image/png"})}
function download(file:File){const url=URL.createObjectURL(file),anchor=document.createElement("a");anchor.href=url;anchor.download=file.name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function ShareSignalPage(){const id=useSearchParams().get("id");const[signal,setSignal]=useState<Signal>(),[error,setError]=useState(""),[working,setWorking]=useState(false);useEffect(()=>{fetch("/api/signals?role=sender").then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load this signal.");const item=(data.signals as Signal[]).find(row=>row.id===id);if(!item)throw new Error("Signal not found.");setSignal(item)}).catch(e=>setError(e.message))},[id]);const text=signal?`Hello ${signal.target_handle} — I just funded a ${money(signal.amount_atomic).toFixed(2)} tUSDT request for you on Renda Signal. All you have to do to claim it is “${signal.title}”. View and accept it here: https://nimiq-quest.nsomiari.chatgpt.site/explore`:"";
function postToX(){window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer")}
async function saveCard(){if(!signal)return;setWorking(true);try{download(await makeCard(signal))}catch(e){setError(e instanceof Error?e.message:"Could not save the image.")}finally{setWorking(false)}}
if(error&&!signal)return <section className="app-empty"><span className="eyebrow">SHARING UNAVAILABLE</span><h1>We couldn’t load this signal.</h1><p>{error}</p><Link className="cta lime" href="/x/sent">Go to sent signals</Link></section>;if(!signal)return <section className="app-empty"><span className="eyebrow">PREPARING SHARE</span><h1>Building your funded offer…</h1></section>;
return <section className="share-screen"><div className="share-copy"><span className="eyebrow">FUNDED ON-CHAIN</span><h1>Now get their<br/><em>attention.</em></h1><p>Your request is funded. Post it so {signal.target_handle} sees the offer and can accept it.</p><div className="simple-share"><button className="primary" onClick={postToX}>Post message to X →</button><div className="image-suggestion"><span>MAKE YOUR POST STAND OUT</span><strong>Add the Renda offer image to your tweet.</strong><p>Download it, then attach it inside the X composer.</p><button className="image-download" onClick={saveCard} disabled={working}>{working?"Creating image…":"Download Renda image ↓"}</button></div></div>{error&&<p className="inline-notice">{error}</p>}<Link href="/x/sent">Skip for now →</Link></div><div className="offer-preview"><div className="offer-brand">RENDA SIGNAL <span>FUNDED</span></div><p>FOR {signal.target_handle}</p><h2>{signal.title}</h2><div className="offer-metrics"><div><small>TOTAL LOCKED</small><strong>{money(signal.amount_atomic).toFixed(2)} tUSDT</strong></div><div><small>DELIVERY REWARD</small><strong>{(money(signal.amount_atomic)-money(signal.attention_atomic)).toFixed(2)} tUSDT</strong></div></div><footer>POLYGON AMOY · DUE {due(signal.deliver_by)}</footer></div></section>}
