import { env } from "cloudflare:workers";
import { addressFromPublicKey, ensureNimiqIdentitySchema, normalizeNimiqAddress } from "@/lib/nimiq-identity";
import { decodeTransactionData, ensureNimiqPaymentSchema, getNimiqPaymentConfig, getNimiqTransaction, normalizeNimAddress, transactionIncluded } from "@/lib/nimiq-payments";
import { getCookie, readSession } from "@/lib/x-auth";

type Row=Record<string,string|number>;
async function base(request:Request){const db=(env as unknown as{DB?:D1Database}).DB,profile=await readSession(getCookie(request,"renda_x_session"));if(!db||!profile)return null;await ensureNimiqPaymentSchema(db);await ensureNimiqIdentitySchema(db);return{db,profile}}
async function verifiedAddress(db:D1Database,xId:string){const row=await db.prepare("SELECT address,public_key FROM nimiq_identities WHERE x_user_id=?").bind(xId).first<{address:string;public_key:string}>();if(!row)return null;try{return normalizeNimiqAddress(addressFromPublicKey(row.public_key))===normalizeNimiqAddress(row.address)?row.address:null}catch{return null}}
const txValue=(tx:Row)=>BigInt(String(tx.value??0));

export async function GET(request:Request){const ctx=await base(request);if(!ctx)return Response.json({error:"Sign in with X first."},{status:401});const url=new URL(request.url);if(url.searchParams.get("admin")!=="1")return Response.json({error:"Unknown request."},{status:400});const address=await verifiedAddress(ctx.db,ctx.profile.id),config=getNimiqPaymentConfig();if(!address||normalizeNimAddress(address)!==normalizeNimAddress(config.escrowAddress))return Response.json({error:"Verify the Renda escrow account to open this console."},{status:403});const rows=await ctx.db.prepare("SELECT s.*,p.payment_mode,p.payout_hash,p.refund_hash FROM signals s JOIN signal_payment_profiles p ON p.signal_id=s.id WHERE p.payment_mode='nim' AND s.status IN ('payout_pending','refund_pending') ORDER BY s.updated_at ASC").all<Row>();return Response.json({signals:rows.results,config})}

export async function POST(request:Request){const ctx=await base(request);if(!ctx)return Response.json({error:"Sign in with X first."},{status:401});const body=await request.json() as{id?:string;action?:"fund"|"accept"|"approve"|"refund"|"settle";txHash?:string;outcome?:"pay"|"refund"};if(!body.id||!body.action)return Response.json({error:"Missing NIM action."},{status:400});const signal=await ctx.db.prepare("SELECT s.*,p.payment_mode,p.payout_hash,p.refund_hash FROM signals s JOIN signal_payment_profiles p ON p.signal_id=s.id WHERE s.id=? AND p.payment_mode='nim'").bind(body.id).first<Row>();if(!signal)return Response.json({error:"NIM request not found."},{status:404});const now=Math.floor(Date.now()/1000),isEmployer=String(signal.sender_x_id)===ctx.profile.id,isRecipient=String(signal.target_handle).toLowerCase()===`@${ctx.profile.username}`.toLowerCase();
 if(body.action==="fund"){if(!isEmployer||!["draft","funding_pending"].includes(String(signal.status))||!body.txHash)return Response.json({error:"This request cannot be funded."},{status:403});try{const tx=await getNimiqTransaction(body.txHash),config=getNimiqPaymentConfig();if(!transactionIncluded(tx))throw new Error("The NIM transaction is not confirmed yet.");if(normalizeNimAddress(String(tx.sender||""))!==normalizeNimAddress(String(signal.employer_wallet)))throw new Error("The payment came from another Nimiq account.");if(normalizeNimAddress(String(tx.recipient||""))!==normalizeNimAddress(config.escrowAddress))throw new Error("The payment was not sent to the Renda escrow account.");if(txValue(tx as Row)!==BigInt(String(signal.amount_atomic)))throw new Error("The NIM payment amount does not match this request.");if(decodeTransactionData(tx.data)!==`RENDA:${body.id}`)throw new Error("The payment reference does not match this request.");const duplicate=await ctx.db.prepare("SELECT id FROM signals WHERE funding_hash=? AND id<>?").bind(body.txHash,body.id).first();if(duplicate)throw new Error("This NIM transaction is already attached to another request.");await ctx.db.batch([ctx.db.prepare("UPDATE signals SET funding_hash=?,status='funded',updated_at=? WHERE id=?").bind(body.txHash,now,body.id),ctx.db.prepare("UPDATE signal_payment_profiles SET updated_at=? WHERE signal_id=?").bind(now,body.id)]);return Response.json({status:"funded",fundingHash:body.txHash})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not verify NIM funding."},{status:400})}}
 if(body.action==="accept"){if(!isRecipient||String(signal.status)!=="funded")return Response.json({error:"This request cannot be accepted."},{status:403});const address=await verifiedAddress(ctx.db,ctx.profile.id);if(!address)return Response.json({error:"Approve the Nimiq Pay identity request first."},{status:403});await ctx.db.prepare("UPDATE signals SET employee_wallet=?,status='accepted',updated_at=? WHERE id=?").bind(address,now,body.id).run();return Response.json({status:"accepted"})}
 if(body.action==="approve"){if(!isEmployer||String(signal.status)!=="submitted")return Response.json({error:"Only the employer can approve submitted work."},{status:403});await ctx.db.prepare("UPDATE signals SET status='payout_pending',updated_at=? WHERE id=?").bind(now,body.id).run();return Response.json({status:"payout_pending"})}
 if(body.action==="refund"){const eligible=String(signal.status)==="declined"||(String(signal.status)==="funded"&&Number(signal.accept_by)<now);if(!isEmployer||!eligible)return Response.json({error:"This request is not eligible for a refund."},{status:403});await ctx.db.prepare("UPDATE signals SET status='refund_pending',updated_at=? WHERE id=?").bind(now,body.id).run();return Response.json({status:"refund_pending"})}
 if(body.action==="settle"){const admin=await verifiedAddress(ctx.db,ctx.profile.id),config=getNimiqPaymentConfig();if(!admin||normalizeNimAddress(admin)!==normalizeNimAddress(config.escrowAddress)||!body.txHash||!body.outcome)return Response.json({error:"Authorize the Renda escrow account first."},{status:403});const expectedStatus=body.outcome==="pay"?"payout_pending":"refund_pending";if(String(signal.status)!==expectedStatus)return Response.json({error:"This settlement is no longer pending."},{status:409});try{const tx=await getNimiqTransaction(body.txHash);if(!transactionIncluded(tx))throw new Error("The settlement transaction is not confirmed yet.");const recipient=body.outcome==="pay"?String(signal.employee_wallet):String(signal.employer_wallet);if(normalizeNimAddress(String(tx.sender||""))!==normalizeNimAddress(config.escrowAddress)||normalizeNimAddress(String(tx.recipient||""))!==normalizeNimAddress(recipient)||txValue(tx as Row)!==BigInt(String(signal.amount_atomic)))throw new Error("The settlement transaction does not match the pending payment.");if(decodeTransactionData(tx.data)!==`RENDA-${body.outcome.toUpperCase()}:${body.id}`)throw new Error("The settlement payment reference is incorrect.");await ctx.db.batch([ctx.db.prepare(`UPDATE signals SET status='${body.outcome==="pay"?"paid":"refunded"}',updated_at=? WHERE id=?`).bind(now,body.id),ctx.db.prepare(`UPDATE signal_payment_profiles SET ${body.outcome==="pay"?"payout_hash":"refund_hash"}=?,updated_at=? WHERE signal_id=?`).bind(body.txHash,now,body.id),ctx.db.prepare("INSERT OR IGNORE INTO signal_transactions (id,signal_id,action,tx_hash,created_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),body.id,body.outcome,body.txHash,now)]);return Response.json({status:body.outcome==="pay"?"paid":"refunded"})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not verify settlement."},{status:400})}}
 return Response.json({error:"Unknown NIM action."},{status:400})
}
